language: php
sudo: false

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - nightly

env:
  - NO_INTERACTION=1

before_script:
  - phpize
  - EXTRA_LDFLAGS="-precious-files-regex .libs/geospatial.gcno" LDFLAGS="-lgcov" CFLAGS="-Wall -ggdb3 -fno-strict-aliasing -coverage -O0" ./configure --enable-geospatial
  - make -j 5 test && if ls tests/*.diff >/dev/null 2>&1; then echo "Tests failed" && cat tests/*.diff && exit 1; fi
  - gcov --object-directory .libs *.c
  - bash <(curl -s https://codecov.io/bash)

script:
  - make install
  - echo "extension = geospatial.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
